---

- include: "{{source_path}}/taskqueue.yml"
  vars:
    standalone: yes
    unversioned_files:
      - {'src': "{{inventory_dir}}/../config_files/production_config.yaml", 'dest': 'etc/config.yaml'}